ALTER TABLE FILM
    ADD CONSTRAINT CHK_FILM_DUREE
    CHECK (Duree > 0);

ALTER TABLE FILM
    ADD CONSTRAINT CHK_FILM_DUREE_MAX
    CHECK (Duree <= 600);

ALTER TABLE FILM
    ADD CONSTRAINT CHK_FILM_PAS_SUITE_DE_SOI
    CHECK (id_film_precedent IS NULL OR id_film_precedent <> id_film);

ALTER TABLE FILM
    ADD CONSTRAINT CHK_FILM_GENRE
    CHECK (Genre IN (
        'Action', 'Aventure', 'Animation', 'Comédie', 'Documentaire',
        'Drame', 'Fantastique', 'Horreur', 'Romance', 'Science-Fiction',
        'Thriller', 'Western', 'Policier', 'Biopic', 'Musical'
    ));


ALTER TABLE FILM
    ADD CONSTRAINT CHK_FILM_DATE_SORTIE_MIN
    CHECK (Date_sortie >= '1895-12-28');


ALTER TABLE SALLE
    ADD CONSTRAINT CHK_SALLE_NUMERO
    CHECK (numero_salle > 0);

ALTER TABLE SALLE
    ADD CONSTRAINT CHK_SALLE_CAPACITE
    CHECK (Capacite > 0);

ALTER TABLE SALLE
    ADD CONSTRAINT CHK_SALLE_CAPACITE_MAX
    CHECK (Capacite <= 1000);

ALTER TABLE SALLE
    ADD CONSTRAINT CHK_SALLE_TYPE_PROJECTEUR
    CHECK (Type_projecteur IN ('Laser', 'Numérique', '3D', 'IMAX', '4DX'));



ALTER TABLE EMPLOYE
    ADD CONSTRAINT CHK_EMPLOYE_ROLE
    CHECK (Role IN ('Projectionniste', 'Accueil', 'Manager', 'Technicien', 'Caissier'));

ALTER TABLE EMPLOYE
    ADD CONSTRAINT CHK_EMPLOYE_DATE_EMBAUCHE_MIN
    CHECK (Date_embauche >= '1900-01-01');

ALTER TABLE EMPLOYE
    ADD CONSTRAINT CHK_EMPLOYE_DATE_EMBAUCHE
    CHECK (Date_embauche <= CURRENT_DATE);

ALTER TABLE EMPLOYE
    ADD CONSTRAINT CHK_EMPLOYE_NOM
    CHECK (LENGTH(TRIM(Nom)) > 0);

ALTER TABLE EMPLOYE
    ADD CONSTRAINT CHK_EMPLOYE_PRENOM
    CHECK (LENGTH(TRIM(Prenom)) > 0);



ALTER TABLE CLIENT
    ADD CONSTRAINT CHK_CLIENT_NOM
    CHECK (LENGTH(TRIM(Nom)) > 0);

ALTER TABLE CLIENT
    ADD CONSTRAINT CHK_CLIENT_PRENOM
    CHECK (LENGTH(TRIM(Prenom)) > 0);

ALTER TABLE CLIENT
    ADD CONSTRAINT CHK_CLIENT_EMAIL_FORMAT
    CHECK (
        Email LIKE '%@%.%'
        AND Email NOT LIKE '@%'
        AND Email NOT LIKE '%@'
    );

ALTER TABLE CLIENT
    ADD CONSTRAINT CHK_CLIENT_DATE_NAISSANCE
    CHECK (Date_naissance < CURRENT_DATE);

ALTER TABLE CLIENT
    ADD CONSTRAINT CHK_CLIENT_AGE_MIN
    CHECK (Date_naissance <= CURRENT_DATE - INTERVAL 12 YEAR);

ALTER TABLE CLIENT
    ADD CONSTRAINT CHK_CLIENT_POINTS
    CHECK (Points_fidelite >= 0);



ALTER TABLE SEANCE
    ADD CONSTRAINT CHK_SEANCE_PRIX
    CHECK (Prix_base > 0);

ALTER TABLE SEANCE
    ADD CONSTRAINT CHK_SEANCE_PRIX_MAX
    CHECK (Prix_base <= 50.00);


ALTER TABLE SEANCE
    ADD CONSTRAINT CHK_SEANCE_DATE_MIN
    CHECK (Date_seance >= '2000-01-01');



ALTER TABLE BILLET
    ADD CONSTRAINT CHK_BILLET_MOYEN_PAIEMENT
    CHECK (Moyen_paiement IN (
        'Carte bancaire', 'Espèces', 'Chèque',
        'Carte cadeau', 'Ticket cinéma', 'PayPal',
        'Pass Culture', 'Carte de fidélité'
    ));


ALTER TABLE BILLET
    ADD CONSTRAINT CHK_BILLET_RANGEE
    CHECK (Rangee_siege REGEXP '^[A-Z]{1,2}$');

ALTER TABLE BILLET
    ADD CONSTRAINT CHK_BILLET_NUMERO_SIEGE
    CHECK (Numero_siege > 0);

ALTER TABLE BILLET
    ADD CONSTRAINT CHK_BILLET_NUMERO_SIEGE_MAX
    CHECK (Numero_siege <= 999);

ALTER TABLE BILLET
    ADD CONSTRAINT CHK_BILLET_DATE_ACHAT
    CHECK (Date_achat <= CURRENT_DATE);
